version: '3.8'

services:
  todo-api:
    build:
      context: .
      dockerfile: dockerfile
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://root:foobar@db:5432/tododb?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"